command = "npm run build"
publish = "frontend/public"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/index"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://transcendent-lebkuchen-741286.netlify.app/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "https://transcendent-lebkuchen-741286.netlify.app/allProducts-page.html"
  to = "/allProducts-page.html"
  status = 200
  