command = "npm run build"
publish = "frontend/public"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "frontend/index"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "frontend/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "frontend/allProducts-page.html"
  to = "/allProducts-page.html"
  status = 200
  