command = "npm run build"
publish = "frontend/public"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"

# _redirects

/index        /index.html     200
/about        /about.html     200
